# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-02 01:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.SlugField(max_length=100)),
                ('last_name', models.SlugField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_num', models.IntegerField()),
                ('reason', models.IntegerField(choices=[(1, 'training'), (2, 'event'), (3, 'other')], default=3)),
            ],
        ),
    ]
