# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-17 00:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_horse'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_prefs',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='horse',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
