# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-21 20:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20161017_0033'),
    ]

    operations = [
        migrations.AddField(
            model_name='horse',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='horse',
            name='status',
            field=models.IntegerField(choices=[(1, 'Un-Enrolled'), (2, 'Enrolled'), (3, 'Pending'), (4, 'Completed')], default=1),
        ),
    ]
