# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-29 21:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='address',
            field=models.ForeignKey(default=events.models.get_default_address, on_delete=django.db.models.deletion.SET_DEFAULT, to='events.Address'),
        ),
    ]
