# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-13 00:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0002_auto_20161029_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='waitlist',
            field=models.ManyToManyField(related_name='waitlisted_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='users',
            field=models.ManyToManyField(related_name='enrolled_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
