# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-22 21:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_backup_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=250)),
                ('state', models.CharField(max_length=250)),
                ('zip_code', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='cost',
            field=models.IntegerField(default=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='deposit',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
