# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-07 19:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20161113_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, related_name='enrolled_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='waitlist',
            field=models.ManyToManyField(blank=True, null=True, related_name='waitlisted_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
