# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-22 21:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20161022_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='address',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, to='events.Address'),
            preserve_default=False,
        ),
    ]
