# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-17 22:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.IntegerField()),
                ('amount_charged', models.IntegerField()),
                ('date_billed', models.DateTimeField()),
                ('date_due', models.DateTimeField()),
                ('status', models.IntegerField(choices=[(1, 'Outstanding'), (2, 'Late'), (3, 'PAID')], default=1)),
                ('service', models.IntegerField(choices=[(1, 'Training'), (2, 'Event')], default=1)),
                ('event', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='events.Event')),
                ('horses', models.ManyToManyField(related_name='invoices', to='users.Horse')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
